#!/usr/bin/env bash
# Transforms Markdown format to html for use with md-publisher.
# Requires pandoc, pandoc-crossref, and pandoc-citeproc
# # See https://pandoc.org/MANUAL.html#extension-yaml_metadata_block
set -e
opts=()
opts+=(--standalone)
opts+=(--resource-path "$PWD")
opts+=(--filter pandoc-crossref)
opts+=(--filter pandoc-citeproc)

## Add here your global citation style (if you like)
#opts+=(--csl "$HOME/.csl/science.csl")

## Add here your global BibTex library if you like
#opts+=(--bibliography "$HOME/Documents/BibTex/Zotero_BBT.bib")

opts+=(--from markdown+yaml_metadata_block+implicit_figures+fenced_divs+citations+table_captions)
opts+=(--to html5)
opts+=(--webtex)
opts+=("${@}")
pandoc "${opts[@]}"

